CREATE DATABASE crud;
USE crud;

CREATE TABLE Evenements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR(250) NOT NULL,
    Localisation VARCHAR(250) NOT NULL,
    nb_participant INT,
    Date DATE NOT NULL,
    Image VARCHAR(250) NOT NULL,
    heure TIME NOT NULL
);

CREATE TABLE Sponsor (
    id_sponsor INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(250) NOT NULL,
    Type VARCHAR(250) NOT NULL

);
